Update the pre-commit and github workflow to move pylint to pre-commit.
adafruit/Adafruit_CircuitPython_GPS pull request #59
Opened 2021-03-01 09:58 UTC by lesamouraipourpre

Also, disable duplicate-code check in examples.

2021-03-01 23:15 UTC, dherrada requested changes

2021-03-01 23:15 UTC, dherrada commented on .pre-commit-config.yaml
> +        args: ['([[ ! -d "examples" ]] || for example in $(find . -path "./examples/*.py"); do pylint --disable=missing-docstring,invalid-name,duplicate-code $example; done)']
Hi @lesamouraipourpre Thanks for doing this. Do you think you could try to copy what we've got [here](https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/master/%7B%25%20if%20cookiecutter.library_prefix%20%25%7D%7B%7B%20cookiecutter.library_prefix%20%7C%20capitalize%20%7D%7D_%7B%25%20endif%20%25%7DCircuitPython_%7B%7B%20cookiecutter.library_name%7D%7D/.pre-commit-config.yaml). I think we found another way of getting around the issues with the duplicate-code check without disabling it.

2021-03-02 20:24 UTC, dherrada commented
@lesamouraipourpre Can you check that the changes you're making are the same as the ones in the place I linked? I think they are, but I just wanted you to check as well before I merge.

2021-03-02 21:41 UTC, lesamouraipourpre commented
> 
> @lesamouraipourpre Can you check that the changes you're making are the same as the ones in the place I linked? I think they are, but I just wanted you to check as well before I merge.

Yes, it was essentially a copy-and-paste to add the pylint sections.

Confirmed with:
> 
> diff cookiecutter-adafruit-circuitpython/\{%\ if\ cookiecutter.library_prefix\ %\}\{\{\ cookiecutter.library_prefix\ \|\ capitalize\ \}\}_\{%\ endif\ %\}CircuitPython_\{\{\ cookiecutter.library_name\}\}/.pre-commit-config.yaml Adafruit_CircuitPython_GPS/.pre-commit-config.yaml

2021-05-13 03:27 UTC, jposada202020 commented
@dherrada :) according to what I read I guess we could merge this change. let me know. Thanks!

2021-05-13 20:55 UTC, dherrada commented
Sweet. Looks good. @jposada202020 Thanks for the reminder on this one

2021-05-13 20:55 UTC, merged

2021-05-13 21:47 UTC, jposada202020 commented
No problem :) @dherrada